version: "2.2"
services:
  backend:
    image: chawkighannoudi/back:2
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=peopleDB;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db

  frontend:
    image: chawkighannoudi/front:2
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - db

  db:
    image: chawkighannoudi/db:2
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
