services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=peopleDB;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend

  db:
    build:
      context: ./db
      dockerfile: Dockerfile

    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    
volumes:
  sqlserver_data:
