name: CI/CD Pipeline

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t chawkighannoudi/back:2 ./back
          docker push chawkighannoudi/back:2

      - name: Build and push frontend image
        run: |
          docker build -t chawkighannoudi/front:2 ./front
          docker push chawkighannoudi/front:2

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure (two-container web app)
        run: |
          az webapp config container set \
            --resource-group user\
            --name back \
            --docker-custom-image-name chawkighannoudi/back:2 \
            --docker-registry-server-url https://index.docker.io/v1/ \
            --docker-registry-server-user ${{ secrets.DOCKER_USERNAME }} \
            --docker-registry-server-password ${{ secrets.DOCKER_PASSWORD }}

          az webapp config container set \
            --resource-group user \
            --name front \
            --docker-custom-image-name chawkighannoudi/front:2 \
            --docker-registry-server-url https://index.docker.io/v1/ \
            --docker-registry-server-user ${{ secrets.DOCKER_USERNAME }} \
            --docker-registry-server-password ${{ secrets.DOCKER_PASSWORD }}
