name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: |
          docker build -t chawkighannoudi/back:2 ./back

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend container to Azure
        run: |
          az containerapp update --resource-group user --name back --image chawkighannoudi/back:2

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test Backend Health
        run: |
          echo "Testing backend health..."
          curl -f https://back.agreeablewater-7b00b80b.northeurope.azurecontainerapps.io/api/health || exit 1

  rollback:
    runs-on: ubuntu-latest
    if: failure()
    needs: test
    steps:
      - name: Rollback to previous version
        run: |
          echo "Rolling back to previous deployment..."
          az containerapp update --resource-group user --name back --image chawkighannoudi/back:previous-version-tag
