name: CI/CD Pipeline

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t chawkighannoudi/back:2 ./back
          docker push chawkighannoudi/back:2

      - name: Build and push frontend image
        run: |
          docker build -t chawkighannoudi/front:2 ./front
          docker push chawkighannoudi/front:2
  

  test:
    runs-on: ubuntu-latest
    needs: build
        
    steps:
              - name: Run backend container
                run: docker run -d -p 5000:80 chawkighannoudi/back:2
        
              - name: Check if backend is healthy
                run: |
                  sleep 5
                  curl --fail http://localhost:5000/health || exit 1
        
              - name: Run frontend container
                run: docker run -d -p 8080:80 chawkighannoudi/front:2
        
              - name: Check if frontend is running
                run: |
                  sleep 5
                  curl --fail http://localhost:8080 || exit 1
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend container to Azure
        run: |
          az containerapp update --resource-group user --name back --image chawkighannoudi/back:2

      - name: Deploy frontend container to Azure
        run: |
          az containerapp update --resource-group user --name front --image chawkighannoudi/front:2
      